In [1]:
!pip install emoji==0.6.0

Requirement already satisfied: emoji==0.6.0 in /usr/local/lib/python3.7/dist-packages (0.6.0)

In [2]:
import pandas as pd
import emoji

In [3]:
my_df = pd.read_csv(r'/content/balanced_validation_En.csv')

In [4]:
# Remove emoji from train data

for index, row in my_df.iterrows():
  my_df.at[index, 'tweet'] = emoji.get_emoji_regexp().sub(r'', row['tweet'])

In [5]:
my_df

,Unnamed: 0,Unnamed: 0.1,tweet,sarcastic,rephrase,sarcasm,irony,satire,understatement,overstatement,rhetorical_question
0,2708,2708,The meaning behind Little Talks - @monstersand...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3416,3416,Kyle is out of town so i made a baked ziti and...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3254,3254,Applying for jobs is so weird and feels fake,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,293,293,@lora__ SHOCKED. How am I supposed to tell the...,1,These people were aware of the risks when they...,1.0,0.0,0.0,0.0,0.0,0.0
4,1,1,I love it when professors draw a big question ...,1,I do not like when professors don’t write out ...,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
167,656,656,Is spunk a slur?,1,I am worried that I may have used a slur by sa...,0.0,1.0,0.0,0.0,0.0,1.0
168,1653,1653,OH MY GOD I AM IN LOVE WITH MY FIANCÉ. https:/...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,3074,3074,Just get yer jab and shut yer moof,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,43,43,"I suppose though, we did sign one for the futu...",1,I wish we could have signed a player for the f...,1.0,0.0,0.0,1.0,0.0,0.0
171,2235,2235,i know i’m going through it when i can’t even ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
result = my_df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'rephrase', 'sarcasm', 'irony', 'satire', 'understatement', 'overstatement', 'rhetorical_question'])

In [7]:
result2 = result.rename(columns={"tweet": "texts", "sarcastic": "info"})

In [8]:
result2

                                                 texts  info
0    The meaning behind Little Talks - @monstersand...     0
1    Kyle is out of town so i made a baked ziti and...     0
2         Applying for jobs is so weird and feels fake     0
3    @lora__ SHOCKED. How am I supposed to tell the...     1
4    I love it when professors draw a big question ...     1
..                                                 ...   ...
167                                   Is spunk a slur?     1
168  OH MY GOD I AM IN LOVE WITH MY FIANCÉ. https:/...     0
169                 Just get yer jab and shut yer moof     0
170  I suppose though, we did sign one for the futu...     1
171  i know i’m going through it when i can’t even ...     0

[172 rows x 2 columns]

In [9]:
info_dict_list = [{'label': row['info']} for index, row in result2.iterrows()]

In [10]:
result2['info'] = info_dict_list

In [11]:
result2

                                                 texts          info
0    The meaning behind Little Talks - @monstersand...  {'label': 0}
1    Kyle is out of town so i made a baked ziti and...  {'label': 0}
2         Applying for jobs is so weird and feels fake  {'label': 0}
3    @lora__ SHOCKED. How am I supposed to tell the...  {'label': 1}
4    I love it when professors draw a big question ...  {'label': 1}
..                                                 ...           ...
167                                   Is spunk a slur?  {'label': 1}
168  OH MY GOD I AM IN LOVE WITH MY FIANCÉ. https:/...  {'label': 0}
169                 Just get yer jab and shut yer moof  {'label': 0}
170  I suppose though, we did sign one for the futu...  {'label': 1}
171  i know i’m going through it when i can’t even ...  {'label': 0}

[172 rows x 2 columns]

In [13]:
result2.to_pickle("output.pkl")

In [ ]:
test_result = pd.read_pickle(r'/content/output.pkl')

In [ ]:
test_result

                                                  texts          info
0                          @Dancruz07 Sureeeeeee you do  {'label': 1}
1     @BoardroomBoy Few links for you. To summarise,...  {'label': 1}
2     #bbcqt It sure would be nice if Ms May decided...  {'label': 1}
3     Someone in Walmart asked my mom if I was a boy...  {'label': 0}
4     Being a mom with an autoimmune disease means I...  {'label': 1}
...                                                 ...           ...
1557  i was so bored today that i let my computer re...  {'label': 0}
1558  It is midnight. On a Thursday. My roommates de...  {'label': 0}
1559  when i was taken off anesthesia today, i told ...  {'label': 0}
1560  @savingfilm @_celia_bedelia_ I have zero tampo...  {'label': 0}
1561  people in london are always asking me for dire...  {'label': 0}

[1562 rows x 2 columns]

In [ ]:
import pickle

In [ ]:
with open('/content/output.pkl', 'rb') as dataset:
  data = pickle.load(dataset)

In [ ]:
data

                                                  texts          info
0                          @Dancruz07 Sureeeeeee you do  {'label': 1}
1     @BoardroomBoy Few links for you. To summarise,...  {'label': 1}
2     #bbcqt It sure would be nice if Ms May decided...  {'label': 1}
3     Someone in Walmart asked my mom if I was a boy...  {'label': 0}
4     Being a mom with an autoimmune disease means I...  {'label': 1}
...                                                 ...           ...
1557  i was so bored today that i let my computer re...  {'label': 0}
1558  It is midnight. On a Thursday. My roommates de...  {'label': 0}
1559  when i was taken off anesthesia today, i told ...  {'label': 0}
1560  @savingfilm @_celia_bedelia_ I have zero tampo...  {'label': 0}
1561  people in london are always asking me for dire...  {'label': 0}

[1562 rows x 2 columns]