In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle(r'/content/raw.pickle')

In [29]:
type(df)

dict

In [ ]:
df['info']

In [15]:
my_df = pd.read_csv(r'/content/balanced_train_En.csv')

In [16]:
my_df

,Unnamed: 0,Unnamed: 0.1,tweet,sarcastic,rephrase,sarcasm,irony,satire,understatement,overstatement,rhetorical_question
0,341,341,@Dancruz07 Sureeeeeee you do,1,"I could've replied ""You do not despise me, you...",1.0,0.0,0.0,0.0,0.0,0.0
1,138,138,"@BoardroomBoy Few links for you. To summarise,...",1,"I would omit the ""who'da thunk"" part.",1.0,0.0,0.0,0.0,0.0,1.0
2,241,241,#bbcqt It sure would be nice if Ms May decided...,1,Theresa May just needs to answer the question.,1.0,0.0,0.0,0.0,0.0,0.0
3,1359,1359,Someone in Walmart asked my mom if I was a boy...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,588,588,Being a mom with an autoimmune disease means I...,1,I wouldn't because sarcasm is the only weapon ...,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1557,1635,1635,i was so bored today that i let my computer re...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1558,2306,2306,It is midnight. On a Thursday. My roommates de...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,3149,3149,"when i was taken off anesthesia today, i told ...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,1153,1153,@savingfilm @_celia_bedelia_ I have zero tampo...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,1061,1061,people in london are always asking me for dire...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
result = my_df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'rephrase', 'sarcasm', 'irony', 'satire', 'understatement', 'overstatement', 'rhetorical_question'])

In [18]:
result2 = result.rename(columns={"tweet": "texts", "sarcastic": "info"})

In [19]:
result2

                                                  texts  info
0                          @Dancruz07 Sureeeeeee you do     1
1     @BoardroomBoy Few links for you. To summarise,...     1
2     #bbcqt It sure would be nice if Ms May decided...     1
3     Someone in Walmart asked my mom if I was a boy...     0
4     Being a mom with an autoimmune disease means I...     1
...                                                 ...   ...
1557  i was so bored today that i let my computer re...     0
1558  It is midnight. On a Thursday. My roommates de...     0
1559  when i was taken off anesthesia today, i told ...     0
1560  @savingfilm @_celia_bedelia_ I have zero tampo...     0
1561  people in london are always asking me for dire...     0

[1562 rows x 2 columns]

In [21]:
info_dict_list = [{'label': row['info']} for index, row in result2.iterrows()]

In [23]:
result2['info'] = info_dict_list

In [24]:
result2

                                                  texts          info
0                          @Dancruz07 Sureeeeeee you do  {'label': 1}
1     @BoardroomBoy Few links for you. To summarise,...  {'label': 1}
2     #bbcqt It sure would be nice if Ms May decided...  {'label': 1}
3     Someone in Walmart asked my mom if I was a boy...  {'label': 0}
4     Being a mom with an autoimmune disease means I...  {'label': 1}
...                                                 ...           ...
1557  i was so bored today that i let my computer re...  {'label': 0}
1558  It is midnight. On a Thursday. My roommates de...  {'label': 0}
1559  when i was taken off anesthesia today, i told ...  {'label': 0}
1560  @savingfilm @_celia_bedelia_ I have zero tampo...  {'label': 0}
1561  people in london are always asking me for dire...  {'label': 0}

[1562 rows x 2 columns]

In [25]:
result2.to_pickle("output.pkl")

In [26]:
test_result = pd.read_pickle(r'/content/output.pkl')

In [27]:
test_result

                                                  texts          info
0                          @Dancruz07 Sureeeeeee you do  {'label': 1}
1     @BoardroomBoy Few links for you. To summarise,...  {'label': 1}
2     #bbcqt It sure would be nice if Ms May decided...  {'label': 1}
3     Someone in Walmart asked my mom if I was a boy...  {'label': 0}
4     Being a mom with an autoimmune disease means I...  {'label': 1}
...                                                 ...           ...
1557  i was so bored today that i let my computer re...  {'label': 0}
1558  It is midnight. On a Thursday. My roommates de...  {'label': 0}
1559  when i was taken off anesthesia today, i told ...  {'label': 0}
1560  @savingfilm @_celia_bedelia_ I have zero tampo...  {'label': 0}
1561  people in london are always asking me for dire...  {'label': 0}

[1562 rows x 2 columns]

In [30]:
import pickle

In [33]:
with open('/content/output.pkl', 'rb') as dataset:
  data = pickle.load(dataset)

In [34]:
data

                                                  texts          info
0                          @Dancruz07 Sureeeeeee you do  {'label': 1}
1     @BoardroomBoy Few links for you. To summarise,...  {'label': 1}
2     #bbcqt It sure would be nice if Ms May decided...  {'label': 1}
3     Someone in Walmart asked my mom if I was a boy...  {'label': 0}
4     Being a mom with an autoimmune disease means I...  {'label': 1}
...                                                 ...           ...
1557  i was so bored today that i let my computer re...  {'label': 0}
1558  It is midnight. On a Thursday. My roommates de...  {'label': 0}
1559  when i was taken off anesthesia today, i told ...  {'label': 0}
1560  @savingfilm @_celia_bedelia_ I have zero tampo...  {'label': 0}
1561  people in london are always asking me for dire...  {'label': 0}

[1562 rows x 2 columns]